/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pspcl;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author amandeep
 */
public class admin_form extends javax.swing.JFrame {

    /**
     * Creates new form admin_form
     */
    ArrayList<file_detail> al1 = new ArrayList<>();
    ArrayList<JPanel> al2 = new ArrayList<>();
    int y3=0;
    int bg=0,cycle=0;
    public admin_form() {
        initComponents();
        this.setVisible(true);
        this.setSize(972,486);
        //this.setResizable(false);
        this.setLocation(50, 50);
        
        jScrollPane1.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
       
        fetch_detail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpb1 = new javax.swing.JPanel();
        deletemain = new javax.swing.JButton();
        defaultbt = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        defaultusertf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        defaultbt1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        deletepaymentbt = new javax.swing.JButton();
        updateta = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        gobackbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PSPCL - ADMIN ACCESS");

        jPanel1.setBackground(new java.awt.Color(98, 98, 98));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PSPCL DEFAULTING LIST GENERATOR - ADMIN ACCESS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 418, 29));

        jPanel2.setBackground(new java.awt.Color(45, 84, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECT CYCLE AND BILLING GROUP THAT WANT TO REMOVE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 402, 27));

        jPanel3.setBackground(new java.awt.Color(45, 84, 94));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Billing group");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        jLabel3.setPreferredSize(new java.awt.Dimension(99, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Billing Cycle");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        jLabel4.setPreferredSize(new java.awt.Dimension(97, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Billing Date");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        jLabel5.setPreferredSize(new java.awt.Dimension(91, 28));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jpb1.setBackground(new java.awt.Color(45, 84, 94));

        javax.swing.GroupLayout jpb1Layout = new javax.swing.GroupLayout(jpb1);
        jpb1.setLayout(jpb1Layout);
        jpb1Layout.setHorizontalGroup(
            jpb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        jpb1Layout.setVerticalGroup(
            jpb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jpb1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 356, 249));

        deletemain.setBackground(new java.awt.Color(45, 84, 94));
        deletemain.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        deletemain.setForeground(new java.awt.Color(255, 255, 255));
        deletemain.setText("DELETE ");
        deletemain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletemainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletemainMouseExited(evt);
            }
        });
        deletemain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletemainActionPerformed(evt);
            }
        });
        jPanel2.add(deletemain, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 87, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 41, 406, -1));

        defaultbt.setBackground(new java.awt.Color(45, 84, 94));
        defaultbt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEFAULT USER");

        jButton1.setBackground(new java.awt.Color(45, 84, 94));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SET DEFAULT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout defaultbtLayout = new javax.swing.GroupLayout(defaultbt);
        defaultbt.setLayout(defaultbtLayout);
        defaultbtLayout.setHorizontalGroup(
            defaultbtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultbtLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(defaultbtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(defaultbtLayout.createSequentialGroup()
                        .addComponent(defaultusertf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        defaultbtLayout.setVerticalGroup(
            defaultbtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultbtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(defaultbtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defaultusertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(defaultbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 41, -1, -1));

        defaultbt1.setBackground(new java.awt.Color(45, 84, 94));
        defaultbt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CLICK HERE TO DELETE DATA OF PAYMENT");

        deletepaymentbt.setBackground(new java.awt.Color(45, 84, 94));
        deletepaymentbt.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        deletepaymentbt.setForeground(new java.awt.Color(255, 255, 255));
        deletepaymentbt.setText("DELETE DATA");
        deletepaymentbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletepaymentbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletepaymentbtMouseExited(evt);
            }
        });
        deletepaymentbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletepaymentbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout defaultbt1Layout = new javax.swing.GroupLayout(defaultbt1);
        defaultbt1.setLayout(defaultbt1Layout);
        defaultbt1Layout.setHorizontalGroup(
            defaultbt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultbt1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(defaultbt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deletepaymentbt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        defaultbt1Layout.setVerticalGroup(
            defaultbt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultbt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletepaymentbt)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(defaultbt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 205, -1, -1));
        jPanel1.add(updateta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 196, -1, -1));

        jPanel4.setBackground(new java.awt.Color(45, 84, 94));

        jLabel8.setBackground(new java.awt.Color(45, 84, 94));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GO BACK TO MAIN WINDOW");

        gobackbt.setBackground(new java.awt.Color(45, 84, 94));
        gobackbt.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        gobackbt.setForeground(new java.awt.Color(255, 255, 255));
        gobackbt.setText("GO BACK");
        gobackbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gobackbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gobackbtMouseExited(evt);
            }
        });
        gobackbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gobackbt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gobackbt)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 440, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletemainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletemainActionPerformed
        int a=JOptionPane.showConfirmDialog(updateta,"DO YOU WANT TO DELETE CYCLE "+cycle+" AND BILLING GROUP "+bg+" ?"); 
        if(a==JOptionPane.YES_OPTION)
        {
            try{
                Connection con=new jdbcconnect().initconn();
            String query="delete from pspcl.agg_main_table where billing_group="+bg+" and cycle="+cycle;
            Statement st = con.createStatement();
            boolean p=st.execute(query);
            query="delete from pspcl.payment_update where billing_group="+bg+" and cycle="+cycle;
            st = con.createStatement();
            p=st.execute(query);
            fetch_detail();
            JOptionPane.showMessageDialog(updateta,"DATA OF CYCLE "+cycle+" AND BILLING GROUP "+bg+" DELETED");
            }
            catch(Exception e)
            {
                System.out.println(e);
                JOptionPane.showMessageDialog(updateta,"ERROR IN DELETING THE DATA  -- "+e); 
            }
            
            
        }
        
    }//GEN-LAST:event_deletemainActionPerformed

    private void gobackbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackbtActionPerformed
        this.dispose();
        new main_frame();
    }//GEN-LAST:event_gobackbtActionPerformed

    private void deletepaymentbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletepaymentbtActionPerformed
        int a=JOptionPane.showConfirmDialog(updateta,"DO YOU WANT TO DELETE ALL PAYMENT DATA ?"); 
        if(a==JOptionPane.YES_OPTION)
        {
            try{
                Connection con=new jdbcconnect().initconn();
            String query="truncate table pspcl.stored_payment";
            Statement st = con.createStatement();
            boolean p=st.execute(query);
            fetch_detail();
            JOptionPane.showMessageDialog(updateta,"PAYMENT DATA DELETED");
            query="truncate table pspcl.basic_e_payment";
            st = con.createStatement();
            p=st.execute(query);
            query="truncate table pspcl.basic_cash_payment";
            st = con.createStatement();
            p=st.execute(query);
            
            }
            catch(Exception e)
            {
                System.out.println(e);
                JOptionPane.showMessageDialog(updateta,"ERROR IN TRUNCATE PAYMENT TABLE -- "+e); 
            }
            
            
        }
    }//GEN-LAST:event_deletepaymentbtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user=defaultusertf.getText();
        if(user.length()!=0)
        {
            try{
            Connection con = new jdbcconnect().initconn();

            String query="truncate table pspcl.default_user";
            Statement st1 = con.createStatement();
            boolean p=st1.execute(query);
            System.out.println(p);
            
            query="insert into pspcl.default_user values ('"+user+"')";
            st1 =con.createStatement();
            p= st1.execute(query);
            System.out.println(p);
             JOptionPane.showMessageDialog(updateta,"DEFAULT USERNAME UPDATED SUCCESSFULLY");
            con.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
                JOptionPane.showMessageDialog(updateta,"ERROR IN SETTING DEFAULT USERNAME -- "+e); 
            }
        }
        else
        {
            JOptionPane.showMessageDialog(updateta,"PLEASE ENTER USERNAME FIRST FOR DEFAULT USERNAME");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setForeground(new Color(45,84,94));
        jButton1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setForeground(new Color(255,255,255));
        jButton1.setBackground(new Color(45,84,94));
    }//GEN-LAST:event_jButton1MouseExited

    private void deletepaymentbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletepaymentbtMouseEntered
        deletepaymentbt.setForeground(new Color(45,84,94));
        deletepaymentbt.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_deletepaymentbtMouseEntered

    private void deletepaymentbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletepaymentbtMouseExited
        deletepaymentbt.setForeground(new Color(255,255,255));
        deletepaymentbt.setBackground(new Color(45,84,94));
    }//GEN-LAST:event_deletepaymentbtMouseExited

    private void gobackbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackbtMouseEntered
        gobackbt.setForeground(new Color(45,84,94));
        gobackbt.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_gobackbtMouseEntered

    private void gobackbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackbtMouseExited
        gobackbt.setForeground(new Color(255,255,255));
        gobackbt.setBackground(new Color(45,84,94));
    }//GEN-LAST:event_gobackbtMouseExited

    private void deletemainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletemainMouseEntered
        deletemain.setForeground(new Color(45,84,94));
        deletemain.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_deletemainMouseEntered

    private void deletemainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletemainMouseExited
        deletemain.setForeground(new Color(255,255,255));
        deletemain.setBackground(new Color(45,84,94));
    }//GEN-LAST:event_deletemainMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel defaultbt;
    private javax.swing.JPanel defaultbt1;
    private javax.swing.JTextField defaultusertf;
    private javax.swing.JButton deletemain;
    private javax.swing.JButton deletepaymentbt;
    private javax.swing.JButton gobackbt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpb1;
    private javax.swing.JLabel updateta;
    // End of variables declaration//GEN-END:variables

void fetch_detail()
{
        y3 = 5;
        jpb1.removeAll();
        jpb1.setBounds(0, 0, jScrollPane1.getWidth(), jScrollPane1.getHeight());
        // Dimension d = jp2.getPreferredSize();
        // d.height = d.height + 200;
        jpb1.setPreferredSize(new Dimension(jpb1.getWidth(), jScrollPane1.getHeight()));
        repaint();
        al2.clear();
        al1.clear();
        try{
        Connection con = new jdbcconnect().initconn();
        
        String query="select billing_group,cycle,max(start_date) as date1 from pspcl.agg_main_table group by billing_group,cycle order by billing_group,cycle";
        Statement st1 = con.createStatement();
        ResultSet rs1 =st1.executeQuery(query);
//        con.commit();
        while(rs1.next())
        {
               al1.add(new file_detail(rs1.getInt("billing_group"),rs1.getInt("cycle"),rs1.getString("date1")));
               System.out.println(al1.size());
        }
        LocalDate olddate = LocalDate.parse(al1.get(0).date);
        LocalDate newdate=olddate.minusDays(50);
        
        System.out.println("array completed");
        printfollowing();
        con.close();
        }
        catch(Exception e){
            System.out.println(e);
            
        }
        
        
}
void printfollowing() {
        for (int i = 0; i < al1.size(); i++) {
            JPanel jp = new JPanel();
            al2.add(jp);

           
                jp.setBackground(new Color(49, 61, 75));
           
            Border border;
            border = new BevelBorder(EtchedBorder.RAISED, new Color(63, 50, 80), new Color(213, 213, 213));
            jp.setBorder(border);
            jp.setLayout(null);
            jpb1.add(jp);
            JLabel lbbg = new JLabel(al1.get(i).billing_group+"");
            JLabel lbbc = new JLabel(al1.get(i).billing_cycle+"");
            JLabel lbdate = new JLabel(al1.get(i).date);
            lbbg.setForeground(Color.white);
            lbbc.setForeground(Color.white);
            lbdate.setForeground(Color.white);

            lbbg.setFont(new Font("Berlin Sans FB Demi", Font.PLAIN, 15));
            lbbc.setFont(new Font("Berlin Sans FB Demi", Font.PLAIN, 15));
            lbdate.setFont(new Font("Berlin Sans FB Demi", Font.PLAIN, 15));
            lbbg.setBorder(border);
            lbbc.setBorder(border);
            lbdate.setBorder(border);
            
            lbbg.setHorizontalAlignment(JLabel.CENTER);
            lbbc.setHorizontalAlignment(JLabel.CENTER);
            lbdate.setHorizontalAlignment(JLabel.CENTER);
            
            lbbg.setBounds(4, 5, 100, 30);
            lbbc.setBounds(106, 5, 105, 30);
            lbdate.setBounds(215, 5, 108, 30);

            jp.add(lbbg);
            jp.add(lbbc);
            jp.add(lbdate);

           
            
            jp.addMouseListener(new MouseAdapter() {            // for story photos

                @Override
                public void mouseClicked(MouseEvent e) {

                    
                    new Thread(new Runnable() {
                        public void run() {
                            
                            for(int i=0;i<al2.size();i++)
                            {
                                if(al2.get(i)==jp)
                                {
                                    al2.get(i).setBackground(new Color(98,98,98));
                                }
                                else
                                {
                                    al2.get(i).setBackground(new Color(49, 61, 75));
                                }
                            }
                            
                            JLabel jdate= (JLabel)jp.getComponent(2);
                            String date1=jdate.getText();
                            JLabel jbg= (JLabel)jp.getComponent(0);
                            int bg1=Integer.parseInt(jbg.getText());
                            JLabel jc= (JLabel)jp.getComponent(1);
                            int cycle1=Integer.parseInt(jc.getText());
                            bg=bg1;
                            cycle=cycle1;
//                            bgcb.setSelectedIndex(bg1);
//                            cyclecb.setSelectedIndex(cycle1);
                            
                            System.out.println("bg:cycle:date"+bg+" "+cycle+" "+date1);
                           
//                             LocalDate olddate = LocalDate.parse(date1);
//                             LocalDate newdate=olddate.minusDays(50);
//                            cash_payment_date1.setText(newdate+"");
//                            e_payment_date1.setText(newdate+"");
                        }
                    }).start();
                     }
            });
            

            if (i > 4) {

                Dimension d = jpb1.getPreferredSize();
                d.height = d.height + 40;
                jpb1.setPreferredSize(d);
                jpb1.setBounds(0, 0, jScrollPane1.getWidth(), jpb1.getHeight() + 40);
                System.out.println("yes");
            }
            jp.setBounds(2, y3, jpb1.getWidth() - 2, 40);
            y3 += 40;
            System.out.println("value of y3-----" + y3);
        }
    }

}
