/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pspcl;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amandeep
 */
public class login_in_form extends javax.swing.JFrame {

    /**
     * Creates new form login_in_form
     */
    String username="";
    public login_in_form() {
        this.setVisible(true);
        initComponents();
        this.setResizable(false);
        fetch_default_user();
        passwordpf.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        usernametf = new javax.swing.JTextField();
        passwordpf = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signuppl = new javax.swing.JPanel();
        signupl = new javax.swing.JLabel();
        loginpl = new javax.swing.JPanel();
        loginl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        op = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOG IN");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pspcl/pspcl.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 108, 356, 105));

        jPanel3.setBackground(new java.awt.Color(0, 100, 140));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernametf.setBackground(new java.awt.Color(0, 100, 140));
        usernametf.setForeground(new java.awt.Color(255, 255, 255));
        usernametf.setText("Username");
        usernametf.setBorder(null);
        jPanel3.add(usernametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 84, 209, 27));

        passwordpf.setBackground(new java.awt.Color(0, 100, 140));
        passwordpf.setForeground(new java.awt.Color(255, 255, 255));
        passwordpf.setBorder(null);
        passwordpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordpfKeyPressed(evt);
            }
        });
        jPanel3.add(passwordpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 153, 209, 28));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 180, 140, 20));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 110, 140, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pspcl/iconmonstr-lock-16-24.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pspcl/iconmonstr-user-6-24.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        signuppl.setBackground(new java.awt.Color(0, 100, 140));
        signuppl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        signupl.setBackground(new java.awt.Color(0, 134, 179));
        signupl.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        signupl.setForeground(new java.awt.Color(255, 255, 255));
        signupl.setText("       SIGN UP");
        signupl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signuplMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signuplMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signuplMouseExited(evt);
            }
        });

        javax.swing.GroupLayout signupplLayout = new javax.swing.GroupLayout(signuppl);
        signuppl.setLayout(signupplLayout);
        signupplLayout.setHorizontalGroup(
            signupplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signupl, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        signupplLayout.setVerticalGroup(
            signupplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupplLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(signupl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(signuppl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 90, 30));

        loginpl.setBackground(new java.awt.Color(0, 100, 140));
        loginpl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        loginl.setBackground(new java.awt.Color(255, 255, 255));
        loginl.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        loginl.setForeground(new java.awt.Color(255, 255, 255));
        loginl.setText("         LOG IN");
        loginl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginlMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginplLayout = new javax.swing.GroupLayout(loginpl);
        loginpl.setLayout(loginplLayout);
        loginplLayout.setHorizontalGroup(
            loginplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginl, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        loginplLayout.setVerticalGroup(
            loginplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel3.add(loginpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOG IN");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 180, 60));
        jPanel3.add(op, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Forget Password ?");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 140, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signuplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplMouseClicked
        this.dispose();
        new signup_form(0);
        
        
    }//GEN-LAST:event_signuplMouseClicked

    private void loginlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlMouseClicked
        String username= usernametf.getText();
        String password= passwordpf.getText();
        boolean p=false;
        try{
            Connection con = new jdbcconnect().initconn();
        
        
            String query="select count(*) as count1 from pspcl.user_auth where username= '"+username+"' and password= '"+password+"'";
            Statement st1 = con.createStatement();
            ResultSet rs1 =st1.executeQuery(query);
            
            if(rs1.next())
            {
                if(rs1.getInt("count1")>=1)
                {
                    p=true;
                }
            }
            con.close();
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
        
        if(p==true)
        {
            this.dispose();
            new main_frame();
            
        }
        else
        {
            JOptionPane.showMessageDialog(op,"INCORRECT AUTHENTICATION,PLEASE TRY AGAIN"); 
            passwordpf.setText("");
        }
        
    }//GEN-LAST:event_loginlMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
        new signup_form(1);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void loginlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlMouseEntered
        loginl.setForeground(new Color(0,100,140));
        loginpl.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_loginlMouseEntered

    private void loginlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlMouseExited
        loginl.setForeground(new Color(255,255,255));
        loginpl.setBackground(new Color(0,100,140));
    }//GEN-LAST:event_loginlMouseExited

    private void signuplMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplMouseEntered
        signupl.setForeground(new Color(0,100,140));
        signuppl.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_signuplMouseEntered

    private void signuplMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplMouseExited
        signupl.setForeground(new Color(255,255,255));
        signuppl.setBackground(new Color(0,100,140));
    }//GEN-LAST:event_signuplMouseExited

    private void passwordpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordpfKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            String username= usernametf.getText();
        String password= passwordpf.getText();
        boolean p=false;
        try{
            Connection con = new jdbcconnect().initconn();
        
        
            String query="select count(*) as count1 from pspcl.user_auth where username= '"+username+"' and password= '"+password+"'";
            Statement st1 = con.createStatement();
            ResultSet rs1 =st1.executeQuery(query);
            
            if(rs1.next())
            {
                if(rs1.getInt("count1")>=1)
                {
                    p=true;
                }
            }
            con.close();
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
        
        if(p==true)
        {
            this.dispose();
            new main_frame();
            
        }
        else
        {
            JOptionPane.showMessageDialog(op,"INCORRECT AUTHENTICATION,PLEASE TRY AGAIN"); 
            passwordpf.setText("");
        }
            
        }
    }//GEN-LAST:event_passwordpfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_in_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_in_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_in_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_in_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_in_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginl;
    private javax.swing.JPanel loginpl;
    private javax.swing.JLabel op;
    private javax.swing.JPasswordField passwordpf;
    private javax.swing.JLabel signupl;
    private javax.swing.JPanel signuppl;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
    void fetch_default_user()
    {
        
       try{
        Connection con = new jdbcconnect().initconn();
        
        String query="select username from pspcl.default_user";
        Statement st1 = con.createStatement();
        ResultSet rs1 =st1.executeQuery(query);
        if(rs1.next())
        {
           username=rs1.getString("username");
           usernametf.setText(username);
        }
        
        con.close();
    }
        catch(Exception e)
        {
            System.out.println(e);
        }
        

    }
}
