/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pspcl;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JLabel;
import javax.swing.JPanel;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author amandeep
 */
public class main_frame extends javax.swing.JFrame {

    ArrayList<file_detail> al1 = new ArrayList<>();
    int y3=0;
    String bill_date;
    /**
     * Creates new form main_frame
     */
    public main_frame() {
        initComponents();
        this.setVisible(true);
        this.setSize(697,414);
        this.setResizable(false);
        this.setLocation(400, 50);
        jScrollPane1.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
        exit_button.setVisible(true); 
        
        e_payment_date();
        fetch_detail();
        cash_payment_date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        exit_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpb1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        e_payment_date = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        e_payment_date1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cash_payment_date1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cash_payment_date = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("pspcl");
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(null);

        exit_button.setText("X");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(exit_button);
        exit_button.setBounds(650, 0, 50, 23);

        jPanel2.setBackground(new java.awt.Color(153, 133, 143));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Billing group");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        jLabel3.setPreferredSize(new java.awt.Dimension(99, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Billing Cycle");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        jLabel4.setPreferredSize(new java.awt.Dimension(97, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Billing Date");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        jLabel5.setPreferredSize(new java.awt.Dimension(91, 28));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 370, 30);

        jLabel1.setText("pspcl");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 180, 20);

        javax.swing.GroupLayout jpb1Layout = new javax.swing.GroupLayout(jpb1);
        jpb1.setLayout(jpb1Layout);
        jpb1Layout.setHorizontalGroup(
            jpb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        jpb1Layout.setVerticalGroup(
            jpb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jpb1);
        jpb1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 90, 370, 180);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cash-payment range");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 60, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-payment range");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 60, 130, 30);

        e_payment_date.setBackground(new java.awt.Color(109, 121, 147));
        e_payment_date.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        e_payment_date.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(e_payment_date);
        e_payment_date.setBounds(420, 120, 90, 20);

        jLabel7.setBackground(new java.awt.Color(109, 121, 147));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("To:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 120, 30, 20);

        e_payment_date1.setBackground(new java.awt.Color(109, 121, 147));
        e_payment_date1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        e_payment_date1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(e_payment_date1);
        e_payment_date1.setBounds(420, 100, 90, 20);

        jLabel8.setBackground(new java.awt.Color(109, 121, 147));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("From:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(530, 100, 40, 20);

        cash_payment_date1.setBackground(new java.awt.Color(109, 121, 147));
        cash_payment_date1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cash_payment_date1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cash_payment_date1);
        cash_payment_date1.setBounds(570, 100, 100, 20);

        jLabel9.setBackground(new java.awt.Color(109, 121, 147));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("From:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 100, 40, 20);

        jLabel10.setBackground(new java.awt.Color(109, 121, 147));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("To:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 120, 30, 20);

        jPanel1.setBackground(new java.awt.Color(109, 121, 147));

        cash_payment_date.setBackground(new java.awt.Color(109, 121, 147));
        cash_payment_date.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cash_payment_date.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(cash_payment_date, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(cash_payment_date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(380, 50, 310, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cash_payment_date;
    private javax.swing.JLabel cash_payment_date1;
    private javax.swing.JLabel e_payment_date;
    private javax.swing.JLabel e_payment_date1;
    private javax.swing.JButton exit_button;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpb1;
    // End of variables declaration//GEN-END:variables


void fetch_detail()
{
        y3 = 5;
        jpb1.removeAll();
        jpb1.setBounds(0, 0, jScrollPane1.getWidth(), jScrollPane1.getHeight());
        // Dimension d = jp2.getPreferredSize();
        // d.height = d.height + 200;
        jpb1.setPreferredSize(new Dimension(jpb1.getWidth(), jScrollPane1.getHeight()));
        repaint();

        al1.clear();
        try{
        Connection con = new jdbcconnect().initconn();
        
        String query="select billing_group,cycle,max(start_date) as date1 from pspcl.agg_main_table group by billing_group,cycle order by billing_group,cycle";
        Statement st1 = con.createStatement();
        ResultSet rs1 =st1.executeQuery(query);
//        con.commit();
        while(rs1.next())
        {
               al1.add(new file_detail(rs1.getInt("billing_group"),rs1.getInt("cycle"),rs1.getString("date1")));
               System.out.println(al1.size());
        }
        System.out.println("array completed");
        printfollowing();
        
        }
        catch(Exception e){
            System.out.println(e);
        }
        
}
void printfollowing() {
        for (int i = 0; i < al1.size(); i++) {
            JPanel jp = new JPanel();
            

            if (i % 2 == 0) {
                jp.setBackground(new Color(109, 121, 147));
            } else {
                jp.setBackground(new Color(182, 161, 158));
            }
            Border border;
            border = new BevelBorder(EtchedBorder.RAISED, new Color(63, 50, 80), new Color(213, 213, 213));
            jp.setBorder(border);
            jp.setLayout(null);
            jpb1.add(jp);
            JLabel lbbg = new JLabel(al1.get(i).billing_group+"");
            JLabel lbbc = new JLabel(al1.get(i).billing_cycle+"");
            JLabel lbdate = new JLabel(al1.get(i).date);
            lbbg.setForeground(Color.white);
            lbbc.setForeground(Color.white);
            lbdate.setForeground(Color.white);

            lbbg.setFont(new Font("Berlin Sans FB Demi", Font.PLAIN, 15));
            lbbc.setFont(new Font("Berlin Sans FB Demi", Font.PLAIN, 15));
            lbdate.setFont(new Font("Berlin Sans FB Demi", Font.PLAIN, 15));
            lbbg.setBorder(border);
            lbbc.setBorder(border);
            lbdate.setBorder(border);
            
            lbbg.setHorizontalAlignment(JLabel.CENTER);
            lbbc.setHorizontalAlignment(JLabel.CENTER);
            lbdate.setHorizontalAlignment(JLabel.CENTER);
            
            lbbg.setBounds(4, 5, 100, 30);
            lbbc.setBounds(106, 5, 105, 30);
            lbdate.setBounds(215, 5, 108, 30);

            jp.add(lbbg);
            jp.add(lbbc);
            jp.add(lbdate);

           
            
            jp.addMouseListener(new MouseAdapter() {            // for story photos

                @Override
                public void mouseClicked(MouseEvent e) {

                    
                    new Thread(new Runnable() {
                        public void run() {
                            
                            JLabel jdate= (JLabel)jp.getComponent(2);
                            String date1=jdate.getText();
                            System.out.println("value"+ date1);
                             LocalDate olddate = LocalDate.parse(date1);
                             LocalDate newdate=olddate.minusDays(50);
                            cash_payment_date1.setText(newdate+"");
                            e_payment_date1.setText(newdate+"");
                        }
                    }).start();
                     }
            });
            

            if (i > 4) {

                Dimension d = jpb1.getPreferredSize();
                d.height = d.height + 40;
                jpb1.setPreferredSize(d);
                jpb1.setBounds(0, 0, jScrollPane1.getWidth(), jpb1.getHeight() + 40);
                System.out.println("yes");
            }
            jp.setBounds(2, y3, jpb1.getWidth() - 2, 40);
            y3 += 50;
            System.out.println("value of y3-----" + y3);
        }
    }
                    
void e_payment_date()
{
    try{
        Connection con = new jdbcconnect().initconn();
        
        String query="select max(receiptdate) as date1 from pspcl.basic_e_payment";
        Statement st1 = con.createStatement();
        ResultSet rs1 =st1.executeQuery(query);
        String date ="";
//        con.commit();
        if(rs1.next())
        {
            date=rs1.getString("date1");
        }
        e_payment_date.setText(date);
        
    }
        catch(Exception e)
        {
            
        }
   
}

void cash_payment_date()
{
    try{
        Connection con = new jdbcconnect().initconn();
        
        String query="select max(receiptdate) as date1 from pspcl.basic_cash_payment";
        Statement st1 = con.createStatement();
        ResultSet rs1 =st1.executeQuery(query);
        String date ="";
//        con.commit();
        if(rs1.next())
        {
            date=rs1.getString("date1");
        }
        cash_payment_date.setText(date);
    }
        catch(Exception e)
        {
            
        }
   
}

}



