/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pspcl;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amandeep
 */
public class signup_form extends javax.swing.JFrame {
    
    int key;
    /**
     * Creates new form login_in_form
     */
    //key==0 -> signup and key==1 ->forget password
    public signup_form(int key) {
        initComponents();
        this.setVisible(true);
        this.key=key;
        this.setResizable(false);
        if(this.key==0)
        {
            headlb.setText("SIGN UP");
            signupl.setText("       SIGN UP");
        }
        else
        {
            headlb.setText("CHANGES AUTHENTICATION");
            signupl.setText("       SAVE");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        usernametf = new javax.swing.JTextField();
        adminpa = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signuppl = new javax.swing.JPanel();
        signupl = new javax.swing.JLabel();
        loginpl = new javax.swing.JPanel();
        loginl = new javax.swing.JLabel();
        headlb = new javax.swing.JLabel();
        passwordpa = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        op = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UPDATING CREDENTIALS");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pspcl/pspcl.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 108, 356, 105));

        jPanel3.setBackground(new java.awt.Color(0, 100, 140));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernametf.setBackground(new java.awt.Color(0, 100, 140));
        usernametf.setForeground(new java.awt.Color(255, 255, 255));
        usernametf.setText("Username");
        usernametf.setBorder(null);
        jPanel3.add(usernametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 84, 209, 27));

        adminpa.setBackground(new java.awt.Color(0, 100, 140));
        adminpa.setForeground(new java.awt.Color(255, 255, 255));
        adminpa.setText("password");
        adminpa.setBorder(null);
        adminpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpaActionPerformed(evt);
            }
        });
        jPanel3.add(adminpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 190, 209, 28));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 220, 140, 20));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 115, 140, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pspcl/iconmonstr-lock-16-24.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pspcl/iconmonstr-user-6-24.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        signuppl.setBackground(new java.awt.Color(0, 100, 140));
        signuppl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        signupl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        signupl.setForeground(new java.awt.Color(255, 255, 255));
        signupl.setText("       SIGN UP");
        signupl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signuplMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signuplMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signuplMouseExited(evt);
            }
        });

        javax.swing.GroupLayout signupplLayout = new javax.swing.GroupLayout(signuppl);
        signuppl.setLayout(signupplLayout);
        signupplLayout.setHorizontalGroup(
            signupplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupplLayout.createSequentialGroup()
                .addComponent(signupl, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        signupplLayout.setVerticalGroup(
            signupplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupplLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(signupl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(signuppl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 90, 30));

        loginpl.setBackground(new java.awt.Color(0, 100, 140));
        loginpl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        loginl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        loginl.setForeground(new java.awt.Color(255, 255, 255));
        loginl.setText("        LOG IN");
        loginl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginlMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginplLayout = new javax.swing.GroupLayout(loginpl);
        loginpl.setLayout(loginplLayout);
        loginplLayout.setHorizontalGroup(
            loginplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginl, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        loginplLayout.setVerticalGroup(
            loginplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel3.add(loginpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 90, 30));

        headlb.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        headlb.setForeground(new java.awt.Color(255, 255, 255));
        headlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headlb.setText("CHANGES AUTHETICATION");
        jPanel3.add(headlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 60));

        passwordpa.setBackground(new java.awt.Color(0, 100, 140));
        passwordpa.setForeground(new java.awt.Color(255, 255, 255));
        passwordpa.setText("password");
        passwordpa.setBorder(null);
        jPanel3.add(passwordpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 140, 209, 28));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 168, 140, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("ADMIN");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 195, -1, -1));
        jPanel3.add(op, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminpaActionPerformed

    private void loginlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlMouseClicked
        this.dispose();
        new login_in_form();
    }//GEN-LAST:event_loginlMouseClicked

    private void signuplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplMouseClicked
        String username= usernametf.getText();
        String password= passwordpa.getText();
        String admin_password= adminpa.getText();
        boolean admin_check=false;
        try{
            Connection con = new jdbcconnect().initconn();
        
            
            String query="select count(*) as count1 from pspcl.admin_auth where password= '"+admin_password+"'";
            Statement st1 = con.createStatement();
            ResultSet rs1 =st1.executeQuery(query);
            
            if(rs1.next())
            {
                if(rs1.getInt("count1")>=1)
                {
                    admin_check=true;
                    System.out.println("admin check  "+admin_check);
                }
            }
            if(admin_check==true&&this.key==0)
            {
                
                query="insert into pspcl.user_auth (username,password) values('"+username+"','"+password+"')";
                st1 = con.createStatement();
                boolean p=st1.execute(query);
                System.out.println("p "+p);
                JOptionPane.showMessageDialog(op,"USER ADDED SUCCESSFULLY"); 
                this.dispose();
                new login_in_form();
            }
            else if(admin_check==true&&this.key==1)
            {
                query="select id from pspcl.user_auth where username='"+username+"'";
                st1 = con.createStatement();
                ResultSet rs=st1.executeQuery(query);
                if(rs.next())
            {
                int id=rs.getInt("id");
                {
                    query="update pspcl.user_auth set username='"+username+"' , password='"+password+"' where id="+id;
                    st1 = con.createStatement();
                    boolean p=st1.execute(query);
                    JOptionPane.showMessageDialog(op,"USER HAS BEEN UPDATED SUCCESSFULLY"); 
                    this.dispose();
                    new login_in_form();
                }
                
            }
            else
                {
                    JOptionPane.showMessageDialog(op,"INCORRECT USERNAME"); 
                }
                
                
                
                
            }
            con.close();
            
        }
        
        catch (Exception e)
        {
            System.out.println(e);
        }
        
        if(admin_check==false)
        {
            JOptionPane.showMessageDialog(op,"PLEASE INSERT CORRECT ADMIN KEY"); 
        }
        
        
    }//GEN-LAST:event_signuplMouseClicked

    private void signuplMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplMouseEntered
        signupl.setForeground(new Color(0,100,140));
        signuppl.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_signuplMouseEntered

    private void signuplMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplMouseExited
        signupl.setForeground(new Color(255,255,255));
        signuppl.setBackground(new Color(0,100,140));
    }//GEN-LAST:event_signuplMouseExited

    private void loginlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlMouseEntered
        loginl.setForeground(new Color(0,100,140));
        loginpl.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_loginlMouseEntered

    private void loginlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlMouseExited
        loginl.setForeground(new Color(255,255,255));
        loginpl.setBackground(new Color(0,100,140));
    }//GEN-LAST:event_loginlMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup_form(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adminpa;
    private javax.swing.JLabel headlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel loginl;
    private javax.swing.JPanel loginpl;
    private javax.swing.JLabel op;
    private javax.swing.JPasswordField passwordpa;
    private javax.swing.JLabel signupl;
    private javax.swing.JPanel signuppl;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
